name = "MineTUKI"
author = "Neo236"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b6f5d4ea9c12a7d448fd792aa16f6b4b316aaaf10323d2b3037258ca6c6b8f0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
