name = "MineTUKI"
author = "Neo236"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "186a666412721be39b7d351b0c859eb7777425c2235e2402d5d8cdbdb3d8a567"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
