name = "MineTUKI"
author = "Neo236"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2cf44ab9d0098edd4f27aca00c333da1bf0f5fcb2b995e55391634bbed169e6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
