modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Neo236/MineTUKI/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/Neo236/MineTUKI"
authors = "Neo236"
logoFile = "fox.png"
description = '''
Mantiene el modpack al dia sin salir del juego. Detecta cuando la lista de
mods cambia en el repositorio y ofrece actualizarla, delegando la descarga
en packwiz.
'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
